### ISSUE TITLE
Error while running the evaluation

### ISSUE THREAD

**Issue by gongye19** [BioASQ/Evaluation-Measures#2]
Dear Sir or Madam,

when i was running:
java -Xmx10G -cp ./flat/BioASQEvaluation/dist/BioASQEvaluation.jar evaluation.EvaluatorTask1b -phaseB -e 5 ./Task6BGoldenEnriched/6B1_golden.json ./BioASQform_BioASQ-answer.json

it met with:
Exception in thread "main" java.lang.NullPointerException
        at evaluation.QuestionAnswerEvaluator.calculatePhaseBMeasuresForPair(QuestionAnswerEvaluator.java:109)
        at evaluation.EvaluatorTask1b.EvaluatePhaseB(EvaluatorTask1b.java:193)
        at evaluation.EvaluatorTask1b.main(EvaluatorTask1b.java:964)

do you have any ideas?

Thank you!

**Comment by inisis** [comment]
Hi, try *git reset --hard cd93f3b8eb290c965d18ef466ee28a0bcf451e5d* and re-run your code
